//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeDogadjajimaProjektniHCI
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Runtime.Serialization.Formatters.Binary;

    [Serializable]    
    public partial class element
    {
        public int idelement { get; set; }
        public string naziv { get; set; }
        public string lokacija { get; set; }
        public string opis { get; set; }
        public System.DateTime datumPocetka { get; set; }
        public System.DateTime datumKraja { get; set; }
        public System.TimeSpan vrijemePocetka { get; set; }
        public System.TimeSpan vrijemeKraja { get; set; }
        public int podDogadjaj_idpodDogadjaj { get; set; }
        public Nullable<bool> obrisan { get; set; }
        public string vrsta { get; set; }
    
        public virtual poddogadjaj poddogadjaj { get; set; }
        public static T DeepClone<T>(T obj)
        {
            using (var ms = new MemoryStream())
            {
                var formatter = new BinaryFormatter();
                formatter.Serialize(ms, obj);
                ms.Position = 0;

                return (T)formatter.Deserialize(ms);
            }
        }
    }
}
