//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeDogadjajimaProjektniHCI
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class fajl
    {
        public int idfajl { get; set; }
        public string naziv { get; set; }
        public byte[] podaci { get; set; }
        public int dogadjaj_iddogadjaj { get; set; }
    
        public virtual dogadjaj dogadjaj { get; set; }
    }
}
