//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeDogadjajimaProjektniHCI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hciEntities1 : DbContext
    {
        public hciEntities1()
            : base("name=hciEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dogadjaj> dogadjajs { get; set; }
        public DbSet<element> elements { get; set; }
        public DbSet<fajl> fajls { get; set; }
        public DbSet<korisnik> korisniks { get; set; }
        public DbSet<poddogadjaj> poddogadjajs { get; set; }
    }
}
